name: Update YouTube Short Title
on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-short-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-oauthlib google-auth-httplib2
      
      - name: Create oauth2.json
        run: |
          echo '${{ secrets.OAUTH_JSON }}' > oauth2.json
          ls -la  # List files to verify creation
          cat oauth2.json | jq .  # Pretty print JSON to verify structure (excluding sensitive data)
      
      - name: Check environment
        run: |
          echo "Python version:"
          python --version
          echo "Pip packages:"
          pip list
          
      - name: Run Python script
        env:
          MY_VIDEO_ID: ${{ secrets.MY_VIDEO_ID }}
        run: python -u update_short_title.py  # -u for unbuffered output
